platform: linux

image_resource:
  type: docker-image
  source:
    repository: szops/twix-shopware-base
    tag: latest
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

inputs:
  - name: push_image

run:
  path: push_image/run-composer.sh

